In [1]:
import pandas as pd
import numpy as np

#### Load Data

In [2]:
flights = pd.read_csv("Dataset/CSV/flights.csv")
airlines = pd.read_csv("Dataset/CSV/airlines.csv")
airports = pd.read_csv("Dataset/CSV/airports.csv")

#### Check Shape

In [3]:
flights.shape, airlines.shape, airports.shape

((1048575, 31), (14, 2), (322, 7))

#### View First Rows

In [4]:
flights.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
airlines.head()

  IATA_CODE                 AIRLINE
0        UA   United Air Lines Inc.
1        AA  American Airlines Inc.
2        US         US Airways Inc.
3        F9  Frontier Airlines Inc.
4        B6         JetBlue Airways

In [6]:
airports.head()

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447

#### Check Column Names

In [7]:
flights.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='object')

In [8]:
airlines.columns

Index(['IATA_CODE', 'AIRLINE'], dtype='object')

In [9]:
airports.columns

Index(['IATA_CODE', 'AIRPORT', 'CITY', 'STATE', 'COUNTRY', 'LATITUDE',
       'LONGITUDE'],
      dtype='object')

#### Check Data Types

In [10]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 31 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   YEAR                 1048575 non-null  int64
 1   MONTH                1048575 non-null  int64
 2   DAY                  1048575 non-null  int64
 3   DAY_OF_WEEK          1048575 non-null  int64
 4   AIRLINE              1048575 non-null  object
 5   FLIGHT_NUMBER        1048575 non-null  int64
 6   TAIL_NUMBER          1040825 non-null  object
 7   ORIGIN_AIRPORT       1048575 non-null  object
 8   DESTINATION_AIRPORT  1048575 non-null  object
 9   SCHEDULED_DEPARTURE  1048575 non-null  int64
 10  DEPARTURE_TIME       1009060 non-null  float64
 11  DEPARTURE_DELAY      1009060 non-null  float64
 12  TAXI_OUT             1008346 non-null  float64
 13  WHEELS_OFF           1008346 non-null  float64
 14  SCHEDULED_TIME       1048573 non-null  float64
 15  ELAPSED_TIME         1005504 non-null  float64
 16  AIR_TIME             1005504 non-null  float64
 17  DISTANCE             1048575 non-null  int64
 18  WHEELS_ON            1007279 non-null  float64
 19  TAXI_IN              1007279 non-null  float64
 20  SCHEDULED_ARRIVAL    1048575 non-null  int64
 21  ARRIVAL_TIME         1007279 non-null  float64
 22  ARRIVAL_DELAY        1005504 non-null  float64
 23  DIVERTED             1048575 non-null  int64
 24  CANCELLED            1048575 non-null  int64
 25  CANCELLATION_REASON  40527 non-null    object
 26  AIR_SYSTEM_DELAY     228528 non-null   float64
 27  SECURITY_DELAY       228528 non-null   float64
 28  AIRLINE_DELAY        228528 non-null   float64
 29  LATE_AIRCRAFT_DELAY  228528 non-null   float64
 30  WEATHER_DELAY        228528 non-null   float64
dtypes: float64(16), int64(10), object(5)
memory usage: 248.0+ MB

In [11]:
airlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   IATA_CODE  14 non-null     object
 1   AIRLINE    14 non-null     object
dtypes: object(2)
memory usage: 356.0+ bytes

In [12]:
airports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   IATA_CODE  322 non-null    object
 1   AIRPORT    322 non-null    object
 2   CITY       322 non-null    object
 3   STATE      322 non-null    object
 4   COUNTRY    322 non-null    object
 5   LATITUDE   319 non-null    float64
 6   LONGITUDE  319 non-null    float64
dtypes: float64(2), object(5)
memory usage: 17.7+ KB

#### Check Missing Values

In [13]:
flights.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER               7750
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           39515
DEPARTURE_DELAY          39515
TAXI_OUT                 40229
WHEELS_OFF               40229
SCHEDULED_TIME               2
ELAPSED_TIME             43071
AIR_TIME                 43071
DISTANCE                     0
WHEELS_ON                41296
TAXI_IN                  41296
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             41296
ARRIVAL_DELAY            43071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    1008048
AIR_SYSTEM_DELAY        820047
SECURITY_DELAY          820047
AIRLINE_DELAY           820047
LATE_AIRCRAFT_DELAY     820047
WEATHER_DELAY           820047
dtype: int64

In [14]:
airlines.isnull().sum()

IATA_CODE    0
AIRLINE      0
dtype: int64

In [15]:
airports.isnull().sum()

IATA_CODE    0
AIRPORT      0
CITY         0
STATE        0
COUNTRY      0
LATITUDE     3
LONGITUDE    3
dtype: int64

#### Why CANCELLATION REASON has missing values

In [16]:
flights['CANCELLED'].value_counts()

CANCELLED
0    1008048
1      40527
Name: count, dtype: int64

- Because flights that were not cancelled should not have a cancellation reason.
- These missing values are meaningful.
- Therefore, can't be filled or removed.

In [17]:
flights['ARRIVAL_DELAY'].describe()

count    1.005504e+06
mean     7.612191e+00
std      4.209367e+01
min     -8.200000e+01
25%     -1.200000e+01
50%     -3.000000e+00
75%      1.200000e+01
max      1.971000e+03
Name: ARRIVAL_DELAY, dtype: float64

In [18]:
flights[['AIR_SYSTEM_DELAY',
         'SECURITY_DELAY',
         'AIRLINE_DELAY',
         'LATE_AIRCRAFT_DELAY',
         'WEATHER_DELAY']].notnull().sum()

AIR_SYSTEM_DELAY       228528
SECURITY_DELAY         228528
AIRLINE_DELAY          228528
LATE_AIRCRAFT_DELAY    228528
WEATHER_DELAY          228528
dtype: int64